### ISSUE TITLE
Ask before deleting the credentials or overwriting them

### ISSUE THREAD

**Issue by zeel-pathak** [zeel-pathak/passdom#2]

**Comment by hemantwasthere** [comment]
Hey @zeel-pathak ,  I would like to work on this issue

**Comment by zeel-pathak** [comment]
The Stage is all yours, go on.....

let me know if you need any help and I will be assigning this issue to you.

**Comment by hemantwasthere** [comment]
Hey @zeel-pathak, I have opened a PR #10 Please check it out and let me know if there are some something that has to be changed

**Comment by zeel-pathak** [comment]
Hey @hemantwasthere , i have already reviewed your work, everything looks good but some minor changes need to be fixed...More about the changes can be foud in pull request
